### ISSUE TITLE
Link posts api

### ISSUE THREAD

**Issue by zi-gae** [Nexters/AZ-RN#105]
# Feature 
Link posts api

## Todos
- [ ] add load post action
- [ ] jwt token header in apiOption
- [ ] add PostDetail navigate
