### ISSUE TITLE
Route PostDetail Event

### ISSUE THREAD

**Issue by zi-gae** [Nexters/AZ-RN#108]
# Feature

Route PostDetail Event

## Todos
- [x] route event
- [x] get comment action
- [x] get post detail action
- [x] add comment, post props on PostDetail

## ETC
change backgroundColor
`#222222` => `#999999`
