### ISSUE TITLE
Add Comment, Post Action for Profile

### ISSUE THREAD

**Issue by zi-gae** [Nexters/AZ-RN#123]
# Feature

Add Comment, Post Action for Profile

## Todos
- [x] my post Action
- [x] my comment Action
- [x] apply Acitons
- [x] Route for post, comment
