### ISSUE TITLE
Bugfix listup

### ISSUE THREAD

**Issue by zi-gae** [Nexters/AZ-RN#141]
## Todos

- [x] Change api call area
- [x] Nickname overflow on Profile
- [x] Comment overflow on PostDetail
- [x] Change logo size
- [x] Change App icon
- [x] Change PostDetail text styles
- [x] Change style for CreateAccount

**Comment by zi-gae** [comment]
- [x] 게시글 스크롤 적용
