### ISSUE TITLE
Add Home page

### ISSUE THREAD

**Issue by zi-gae** [Nexters/AZ-RN#57]
# Feature

Add Home page

## Desciption

Page to be displayed immediately after login

## ToDos
- [x] Root ScrollView
- [x] Level badge component
- [x] gagebar remaining to next stage
- [x] inner ScrollView
- [x] sticky inner ScrollView
- [x] fix gagebar size
