### ISSUE TITLE
Add PostWrite page

### ISSUE THREAD

**Issue by zi-gae** [Nexters/AZ-RN#82]
## Feature 

Add PostWrite page

## Todos 
- [x] add align center TextArea
- [x] refactor Text to clickable
- [x] fix touch area extends in FloatingButton
- [ ] add flexable text size on TextArea
- [x] fix keyboard hide
- [ ] Wrting...
