### ISSUE TITLE
Create initial README.md guidelines

### ISSUE THREAD

**Issue by zi-gae** [Nexters/AZ-RN#9]
## Purpose  

- Organize the README.md is helped to start for newbies 
- We should specify the basic instruction to help to understand our project 

## TODO  

- [ ] Add testing guideline 
- [ ] Add tech stack guideline 
- [ ] Add convention guideline
