### ISSUE TITLE
Apply CreacteAcount api

### ISSUE THREAD

**Issue by zi-gae** [Nexters/AZ-RN#92]
# Feature
Apply CreacteAcount api

## Todos
- [x] create reducer
- [x] create account action
- [ ] identification check action
- [ ] nickname check action
